### PR TITLE
change icons in each category

### PR DESCRIPTION
**Pull request by pivanov**
pls do not merge till @patrykdesign r+ this

### CODE REVIEW

**Comment by pivanov** [comment]
Hey @patrykdesign can you review this changes?

**Comment by patrykdesign** [comment]
+1

**Comment by jedireza** [comment]
Sweet. @pivanov would you like me to merge into my fork now?

**Comment by pivanov** [comment]
@jedireza yeah it will be easy to land all patches from one place :) thanks :)

**Pull request merged**
